name: versa

order:
  - test
  - build
  - deploy

stages:
  test:
    - name: test-task
      image: alpine
      scripts:
        - echo "hello world"
        - sleep 3
        - echo "hello world again"
      tags:
        - always
    - name: failed-task
      image: alpine
      scripts:
        - what?
  build:
    - name: build-task
      image: alpine
      scripts:
        - echo "build task"
  deploy:
    - name: deploy-task
      depends:
        - test:test-task
      image: alpine
      scripts:
        - echo "demo-tag"
      tags:
        - demo-tag
